# Yarn Berry configuration
# This project uses pnpm as the primary package manager.
# This file exists for contributors who prefer yarn.

nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: mixed
